# Copy embedding weights.

In [1]:
import torch

In [2]:
emb1 = torch.nn.Embedding(3,4)
emb2 = torch.nn.Embedding(3,4)

In [4]:
dir(emb1)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_name',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_version',
 'add_module',
 'apply',
 'bfloat16',
 'buffers',
 'children',
 'cpu',
 'cuda',
 'double',
 'dump

In [5]:
emb1.weight

Parameter containing:
tensor([[-0.5733,  0.4727,  2.3292,  0.3882],
        [-0.8442,  0.3685, -0.2390, -0.8850],
        [ 0.9971, -0.3312,  0.9892,  0.7570]], requires_grad=True)

In [6]:
emb2.weight

Parameter containing:
tensor([[-1.5407, -0.5171,  0.1301, -0.0244],
        [-1.3310, -0.6862,  0.4079, -1.3477],
        [ 0.4531, -1.1278, -1.2002,  0.2824]], requires_grad=True)

In [9]:
import copy

In [10]:
emb3 = copy.deepcopy(emb1)

In [11]:
emb3.weight

Parameter containing:
tensor([[-0.5733,  0.4727,  2.3292,  0.3882],
        [-0.8442,  0.3685, -0.2390, -0.8850],
        [ 0.9971, -0.3312,  0.9892,  0.7570]], requires_grad=True)

In [18]:
emb2.from_pretrained(emb1.weight)

Embedding(3, 4)

In [20]:
emb2.weight

Parameter containing:
tensor([[-1.5407, -0.5171,  0.1301, -0.0244],
        [-1.3310, -0.6862,  0.4079, -1.3477],
        [ 0.4531, -1.1278, -1.2002,  0.2824]], requires_grad=True)

In [21]:
emb2 = emb2.from_pretrained(emb1.weight)

In [32]:
emb2.weight

Parameter containing:
tensor([[-0.5733,  0.4727,  2.3292,  0.3882],
        [-0.8442,  0.3685, -0.2390, -0.8850],
        [ 0.9971, -0.3312,  0.9892,  0.7570]])

In [34]:
# no grad.
print(emb1(torch.tensor(0)))
print(emb2(torch.tensor(0)))

tensor([-0.5733,  0.4727,  2.3292,  0.3882], grad_fn=<EmbeddingBackward>)
tensor([-0.5733,  0.4727,  2.3292,  0.3882])


In [25]:
emb2.apply(emb1.parameters)

Embedding(3, 4)

In [26]:
emb2 = emb2.apply(emb1.parameters)

In [31]:
emb3 = torch.nn.Embedding(3,4)
print(emb3.weight)
emb3 = emb3.apply(emb1.parameters)
print(emb3.weight)
print(emb1.weight) # apply dont change weight

Parameter containing:
tensor([[-0.7352,  1.3280, -0.3746,  1.4420],
        [-2.6702, -0.6714,  0.2365,  0.6400],
        [ 1.8743, -0.5686, -1.7243,  0.5487]], requires_grad=True)
Parameter containing:
tensor([[-0.7352,  1.3280, -0.3746,  1.4420],
        [-2.6702, -0.6714,  0.2365,  0.6400],
        [ 1.8743, -0.5686, -1.7243,  0.5487]], requires_grad=True)
Parameter containing:
tensor([[-0.5733,  0.4727,  2.3292,  0.3882],
        [-0.8442,  0.3685, -0.2390, -0.8850],
        [ 0.9971, -0.3312,  0.9892,  0.7570]], requires_grad=True)
