In [1]:
import torch
import numpy as np

In [2]:
a = torch.rand(3,4)
c = torch.angle(a)
c

AttributeError: module 'torch' has no attribute 'angle'

In [3]:
torch.__version__

'1.2.0'

In [6]:
a = torch.ones(3,3)
b = torch.eye(3)
d = torch.addcdiv(a,b,a,value=1)
d

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [8]:
a = torch.tensor([[180.0, -180.0], [360.0, -360.0], [90.0, -90.0]])
torch.deg2rad(a)

AttributeError: module 'torch' has no attribute 'deg2rad'

In [10]:
a = torch.rand(3,4)*40
c = torch.frac(a)
c

tensor([[0.7739, 0.1192, 0.3074, 0.7259],
        [0.3664, 0.9443, 0.1335, 0.7796],
        [0.5701, 0.0990, 0.8846, 0.7255]])

In [17]:
d = torch.arange(1,10,dtype=torch.float)
f = torch.linspace(10,100,9,dtype=torch.float)

In [18]:
weight = torch.full_like(d, 0.1)
g = torch.lerp(d,f,weight)
g

tensor([ 1.9000,  3.9250,  5.9500,  7.9750, 10.0000, 12.0250, 14.0500, 16.0750,
        18.1000])