In [1]:
import torch
import numpy as np

In [2]:
a = torch.rand(3,4)
c = torch.angle(a)
c

AttributeError: module 'torch' has no attribute 'angle'

In [3]:
torch.__version__

'1.2.0'

In [6]:
a = torch.ones(3,3)
b = torch.eye(3)
d = torch.addcdiv(a,b,a,value=1)
d

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [8]:
a = torch.tensor([[180.0, -180.0], [360.0, -360.0], [90.0, -90.0]])
torch.deg2rad(a)

AttributeError: module 'torch' has no attribute 'deg2rad'

In [10]:
a = torch.rand(3,4)*40
c = torch.frac(a)
c

tensor([[0.7739, 0.1192, 0.3074, 0.7259],
        [0.3664, 0.9443, 0.1335, 0.7796],
        [0.5701, 0.0990, 0.8846, 0.7255]])

In [17]:
d = torch.arange(1,10,dtype=torch.float)
f = torch.linspace(10,100,9,dtype=torch.float)

In [18]:
weight = torch.full_like(d, 0.1)
g = torch.lerp(d,f,weight)
g

tensor([ 1.9000,  3.9250,  5.9500,  7.9750, 10.0000, 12.0250, 14.0500, 16.0750,
        18.1000])

In [2]:
dummy = torch.randn(3,4, dtype=torch.float)
dummy

tensor([[ 0.5550,  0.3195, -0.7141,  1.1465],
        [-0.7969,  0.4429, -0.9689,  1.8222],
        [-0.4295, -0.8404,  0.6419,  0.0956]])

In [3]:
a1 = torch.unbind(dummy, 0)
a2 = torch.unbind(dummy, 1)
a1

(tensor([ 0.5550,  0.3195, -0.7141,  1.1465]),
 tensor([-0.7969,  0.4429, -0.9689,  1.8222]),
 tensor([-0.4295, -0.8404,  0.6419,  0.0956]))

In [4]:
a2

(tensor([ 0.5550, -0.7969, -0.4295]),
 tensor([ 0.3195,  0.4429, -0.8404]),
 tensor([-0.7141, -0.9689,  0.6419]),
 tensor([1.1465, 1.8222, 0.0956]))

In [6]:
dummy2 = torch.randint(10, size=(3,4,5))

In [7]:
b0 = torch.unbind(dummy2)
b1 = torch.unbind(dummy2, dim=1)
b2 = torch.unbind(dummy2, dim=2)
print(b0,b1,b2)

(tensor([[8, 7, 0, 6, 0],
        [0, 0, 3, 1, 4],
        [7, 2, 4, 4, 4],
        [7, 1, 8, 0, 2]]), tensor([[0, 9, 3, 1, 8],
        [3, 4, 0, 1, 5],
        [4, 1, 7, 0, 9],
        [1, 5, 9, 6, 8]]), tensor([[5, 2, 3, 3, 3],
        [0, 2, 5, 0, 2],
        [3, 0, 8, 2, 4],
        [8, 5, 0, 0, 0]])) (tensor([[8, 7, 0, 6, 0],
        [0, 9, 3, 1, 8],
        [5, 2, 3, 3, 3]]), tensor([[0, 0, 3, 1, 4],
        [3, 4, 0, 1, 5],
        [0, 2, 5, 0, 2]]), tensor([[7, 2, 4, 4, 4],
        [4, 1, 7, 0, 9],
        [3, 0, 8, 2, 4]]), tensor([[7, 1, 8, 0, 2],
        [1, 5, 9, 6, 8],
        [8, 5, 0, 0, 0]])) (tensor([[8, 0, 7, 7],
        [0, 3, 4, 1],
        [5, 0, 3, 8]]), tensor([[7, 0, 2, 1],
        [9, 4, 1, 5],
        [2, 2, 0, 5]]), tensor([[0, 3, 4, 8],
        [3, 0, 7, 9],
        [3, 5, 8, 0]]), tensor([[6, 1, 4, 0],
        [1, 1, 0, 6],
        [3, 0, 2, 0]]), tensor([[0, 4, 4, 2],
        [8, 5, 9, 8],
        [3, 2, 4, 0]]))


In [16]:
dummy3 = torch.ones(4,4)
dummy4 = torch.full_like(dummy3, 2)
dummy5 = torch.full_like(dummy4, 3)
dummy6 = torch.cat((dummy3, dummy4, dummy5), dim=-2)
dummy6

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [12]:
torch.chunk(dummy3, chunks=4,dim=1)

(tensor([[1.],
         [1.],
         [1.],
         [1.]]),
 tensor([[1.],
         [1.],
         [1.],
         [1.]]),
 tensor([[1.],
         [1.],
         [1.],
         [1.]]),
 tensor([[1.],
         [1.],
         [1.],
         [1.]]))