In [ ]:
# torch.nn.utils
* pack_padded_sequence: 针对已经padding的数据，进行压缩
* pack_sequence:
* pad_packed_sequence: 将packed的数据重新pad，扩展成原有维度。
详细信息可以参考onenote笔记。

In [11]:
import torch 
import torch.nn as nn
import torch.nn.functional as F 

from  torch.nn.utils.rnn import pack_padded_sequence
# pack_padded_sequence: deal with padded_sequece
# return a PackedSequence.

a = torch.tensor([[1,2,3,0,0],
                  [1,2,0,0,0], 
                  [1,0,0,0,0]])
a_len = torch.tensor([3,2,1])

print(a, a_len)

packed = pack_padded_sequence(a, lengths=a_len, batch_first=True)
print(type(packed))

print(packed.data)
# print(packed.__dir__())
print(packed.batch_sizes)


tensor([[1, 2, 3, 0, 0],
        [1, 2, 0, 0, 0],
        [1, 0, 0, 0, 0]]) tensor([3, 2, 1])
<class 'torch.nn.utils.rnn.PackedSequence'>
tensor([1, 1, 1, 2, 2, 3])
tensor([3, 2, 1])


## pack_sequence: 
* Packs a list of variable length Tensors.
* sequences should be a list of Tensors of size L x *, where L is the length of a sequence and * is any number of trailing dimensions, including zero.



In [3]:
from torch.nn.utils.rnn import pack_sequence

t_list = [torch.rand(n) for n in range(1,4)]
print(t_list)
b_pack = pack_sequence(t_list, enforce_sorted=False)
b_pack
# return PackedSequence object.

[tensor([0.0286]), tensor([0.5886, 0.7330]), tensor([0.0881, 0.2555, 0.9989])]

In [10]:
from torch.nn.utils.rnn import pad_packed_sequence
# 必须针对PackedSequence使用；对于变长序列，首先使用pack_sequence, 然后使用pad_packed_sequence
b_unpack = pad_packed_sequence(b_pack, batch_first=True)
b_unpack

(tensor([[0.0286, 0.0000, 0.0000],
         [0.5886, 0.7330, 0.0000],
         [0.0881, 0.2555, 0.9989]]),
 tensor([1, 2, 3]))