## Scatter(dim, index, src)
### 1. create one/multi-hot tesor
### 2. expand dimenson length 

In [1]:
import torch 
import numpy 


## scatter(dim, index, src)

In [2]:
# 1-d case: scatter label into a larger vector
# create one-hot vector
label = torch.randint(184, (8,))
print(label)
b = torch.zeros(184,)
b.scatter_(0, label, 1.0)


tensor([ 63, 147, 147,  47,  61,  89, 151,  98])


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [14]:
# 1-d case: scatter label into a larger vector
# 将一维向量扩展成一个更长的向量
label = torch.randint(184, (8,))
print(label)
b = torch.zeros(184,)
print(b.dtype)
b.scatter_(0, torch.tensor([3,4,6,7,12,34,56,67]), label.float())

tensor([146,  48,  63, 153, 170,  93, 135, 146])
torch.float32


tensor([  0.,   0.,   0., 146.,  48.,   0.,  63., 153.,   0.,   0.,   0.,   0.,
        170.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  93.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 135.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0., 146.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   

In [23]:
# 1-d将一个一维向量在行方向上扩展，分散到不同的行。
# 好像不行啊。
src = torch.rand(4,8)
print(src)
b = torch.zeros(8,8)
index = torch.tensor([[1,3,4,6]]).T
b.scatter_(0, index, src)


tensor([[0.6474, 0.0134, 0.0905, 0.6780, 0.0288, 0.0396, 0.8018, 0.7624],
        [0.0677, 0.6877, 0.2576, 0.6093, 0.7249, 0.6583, 0.5215, 0.6992],
        [0.5815, 0.7585, 0.4401, 0.5629, 0.7449, 0.7052, 0.5525, 0.0437],
        [0.2452, 0.1454, 0.5708, 0.4587, 0.3509, 0.7983, 0.5113, 0.1288]])


tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.6474, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0677, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5815, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2452, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [3]:
# 2-d case
label = torch.randint(184, (8,2))
print(label)
b = torch.zeros(184,2)
b.scatter_(0, label, 1.0)# scatter value alone the dim. dim 0

tensor([[126, 134],
        [ 34, 124],
        [151,  63],
        [ 11, 175],
        [ 41, 108],
        [150, 157],
        [ 59,  65],
        [ 63,  20]])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0

In [4]:
# exercise:
# objs: (O,) values in [0, num_classes)
# obj_to_img: (O,) like: (00000,1111,22,333) lenght=O, 
# output: N*num_classes. Multi-hot matrix.
num_cls = 15
O = 20
objs = torch.randint(num_cls, (O,))
obj_to_img = [0]*5+[1]*4+[2]*2+[3]*3+[4]*(O-14)
print(objs)
print(obj_to_img)

tensor([10,  4,  1,  1, 12,  1,  2,  8,  0, 10, 11,  2,  9,  2, 13, 10,  0, 10,
         7, 13])
[0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4]


In [5]:
from collections import Counter

split_idx = list(Counter(obj_to_img).values())
print(split_idx)
objs_list = objs.split(split_idx)
print(objs_list)

[5, 4, 2, 3, 6]
(tensor([10,  4,  1,  1, 12]), tensor([1, 2, 8, 0]), tensor([10, 11]), tensor([2, 9, 2]), tensor([13, 10,  0, 10,  7, 13]))


In [6]:
multi_hot = []
for label in objs_list:
    tmp = torch.zeros(1, num_cls)
    tmp.scatter_(1, label.unsqueeze(0), 1.0)
    multi_hot.append(tmp)
multi_hot = torch.cat(multi_hot, dim=0)
print(multi_hot)


tensor([[0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.]])


In [30]:
import numpy as np 
a = np.eye(4)
a[[2,3]]=1
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
a[[1,3]][:,[0,2]]=4
a

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])