In [1]:
import torch 
import numpy 


## scatter(dim, index, src)

In [23]:
# 1-d case: scatter label into a larger vector
label = torch.randint(184, (8,))
print(label)
b = torch.zeros(184,)
b.scatter_(0, label, 1.0)


tensor([123, 123,  80, 118,  15,  22,  38,  67])


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [25]:
# 2-d case
label = torch.randint(184, (8,2))
print(label)
b = torch.zeros(184,2)
b.scatter_(0, label, 1.0)# scatter value alone the dim. dim 0

tensor([[ 42,  54],
        [140, 172],
        [ 61, 113],
        [126,  67],
        [158, 116],
        [118,  68],
        [ 77, 100],
        [138, 140]])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.],
        [0

In [28]:
# exercise:
# objs: (O,) values in [0, num_classes)
# obj_to_img: (O,) like: (00000,1111,22,333) lenght=O, 
# output: N*num_classes. Multi-hot matrix.
num_cls = 15
O = 20
objs = torch.randint(num_cls, (O,))
obj_to_img = [0]*5+[1]*4+[2]*2+[3]*3+[4]*(O-14)
print(objs)
print(obj_to_img)

tensor([ 0,  6,  0, 11,  4,  3, 10,  2,  4, 13, 13, 13,  2,  4,  2,  0,  7, 11,
         5, 13])
[0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4]


In [30]:
from collections import Counter

split_idx = list(Counter(obj_to_img).values())
print(split_idx)
objs_list = objs.split(split_idx)
print(objs_list)

[5, 4, 2, 3, 6]
(tensor([ 0,  6,  0, 11,  4]), tensor([ 3, 10,  2,  4]), tensor([13, 13]), tensor([13,  2,  4]), tensor([ 2,  0,  7, 11,  5, 13]))


In [33]:
multi_hot = []
for label in objs_list:
    tmp = torch.zeros(1, num_cls)
    tmp.scatter_(1, label.unsqueeze(0), 1.0)
    multi_hot.append(tmp)
multi_hot = torch.cat(multi_hot, dim=0)
print(multi_hot)


tensor([[1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.]])
