In [1]:
import torch 
import numpy 


## scatter(dim, index, src)

In [2]:
# 1-d case: scatter label into a larger vector
label = torch.randint(184, (8,))
print(label)
b = torch.zeros(184,)
b.scatter_(0, label, 1.0)


tensor([145, 140, 141,  64,  73, 123,  81,  39])


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [3]:
# 2-d case
label = torch.randint(184, (8,2))
print(label)
b = torch.zeros(184,2)
b.scatter_(0, label, 1.0)# scatter value alone the dim. dim 0

tensor([[126, 134],
        [ 34, 124],
        [151,  63],
        [ 11, 175],
        [ 41, 108],
        [150, 157],
        [ 59,  65],
        [ 63,  20]])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0

In [4]:
# exercise:
# objs: (O,) values in [0, num_classes)
# obj_to_img: (O,) like: (00000,1111,22,333) lenght=O, 
# output: N*num_classes. Multi-hot matrix.
num_cls = 15
O = 20
objs = torch.randint(num_cls, (O,))
obj_to_img = [0]*5+[1]*4+[2]*2+[3]*3+[4]*(O-14)
print(objs)
print(obj_to_img)

tensor([10,  4,  1,  1, 12,  1,  2,  8,  0, 10, 11,  2,  9,  2, 13, 10,  0, 10,
         7, 13])
[0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4]


In [5]:
from collections import Counter

split_idx = list(Counter(obj_to_img).values())
print(split_idx)
objs_list = objs.split(split_idx)
print(objs_list)

[5, 4, 2, 3, 6]
(tensor([10,  4,  1,  1, 12]), tensor([1, 2, 8, 0]), tensor([10, 11]), tensor([2, 9, 2]), tensor([13, 10,  0, 10,  7, 13]))


In [6]:
multi_hot = []
for label in objs_list:
    tmp = torch.zeros(1, num_cls)
    tmp.scatter_(1, label.unsqueeze(0), 1.0)
    multi_hot.append(tmp)
multi_hot = torch.cat(multi_hot, dim=0)
print(multi_hot)


tensor([[0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.]])
